### ISSUE TITLE
Report Timer doesn't work good

### ISSUE THREAD

**Issue by DraziV** [jtsalisbury/gmod-report-system#9]
[Reports] You must wait at least 5 minutes to report again! Time left: 1205 minutes.

Can somebody help me please?

**Comment by crazyscouter** [comment]
Hi,

I'm sorry I haven't been on in quite a while. This utility (Report System) was developed a long time ago when I wasn't very good at programming. I would recommend finding another tool for your needs as I am no longer actively working on this.

Sorry & Best Regards
